### PR TITLE
fix cropped borders on mobile

### LINKED ISSUE #301: [Bug] Cropped borders on Obsidian Mobile when choice a different Workspace Layout
**Describe the bug**
On Obsidian Mobile when I choice a different Workspace Layout it looks not very responsive.

**To Reproduce**
1. Enter in Obsidian Mobile App.
2. Enter in style settings.
3. Change Workspace Layout.

**Expected behavior**
Full width notes on Obsidian Mobile and my custom layout in Obsidian Desktop.

**Screenshots**

Style Settings Section

Borders Layout

Cards Layout

Expected layout

### PR DESCRIPTION
**Pull request by iwa**
basically removes all borders and margins when using a phone *(screen width >600px)*

should fix #301

### CODE REVIEW

**Comment by iwa** [comment]
will do other layouts later today

**Comment by iwa** [comment]
only current downside is that it removes the border radius and margins on pc too if the window is slimmer than 600px (which is rare)

dunno if there is a way to apply style only on mobile, but this would at least ease the pain that is using the theme on mobile for now i hope

**Comment by AnubisNekhet** [comment]
> only current downside is that it removes the border radius and margins on pc too if the window is slimmer than 600px (which is rare)
> 
> dunno if there is a way to apply style only on mobile, but this would at least ease the pain that is using the theme on mobile for now i hope

The `<body>` tag uses `.is-tablet` and `.is-mobile` classes for tablet and mobile platforms respectively. I'd consider using those classes instead of `@media` rules.

**Comment by iwa** [comment]
okey i didnt know about that, i'll rewrite the code using that instead, thanks!

**Comment by iwa** [comment]
> The `<body>` tag uses `.is-tablet` and `.is-mobile` classes for tablet and mobile platforms respectively. I'd consider using those classes instead of `@media` rules.

just to add a bit on your comment, it seems that:
- `.is-mobile` is always applied when using the mobile app
- `.is-phone` is applied if it's a phone (>600px width)
- `.is-tablet` is applied otherwise

for now i'll apply the styles using `.is-phone`, but it might be a good idea to add a style setting to let people decide if they want to apply it to either phone, tablet or both?

**Comment by iwa** [comment]
ok so:
- cards layout works fine on PC and Tablet, margins & borders are removed on Phone
- border layout works fine only on PC, margins & borders are removed on Tablet & Phone (might work on a PR to make the border layout looking fine on tablet)

**Comment by AnubisNekhet** [comment]
Looks great, thank you for your contribution!

**Pull request merged**
