### PR TITLE
add setting to auto-hide the tab title bar

### PR DESCRIPTION
**Pull request by pryley**
https://user-images.githubusercontent.com/134939/209706976-c76b6305-64d8-4d32-8a6f-291d1a9bcd54.mp4

### CODE REVIEW

**Comment by pryley** [comment]
This pull request also adds a Makefile to the project, so instead of running `sass src/base.scss theme.css` to build, you just need to run `make build`.

**Comment by AnubisNekhet** [comment]
I can't thank you enough! Absolutely wonderful ❤️

**Comment by jairjacom** [comment]
in my case when enabled, it does not hid the tab title bar but it hides the (don't know what is called) the mini bar in right bottom left corner where backlinks, words count, characters count sit in... maybe one of my snippets that modified the appeareance of such bar?

**Comment by jairjacom** [comment]
Obsidian_GwF7kbEx5l

**Comment by AnubisNekhet** [comment]
You'll need to update the theme to the latest version for this feature 🙂
The option you're talking about is a separate toggle and it's working as intended, hope that helps!

**Comment by jairjacom** [comment]
> You'll need to update the theme to the latest version for this feature 🙂 The option you're talking about is a separate toggle and it's working as intended, hope that helps!

Got it, maybe my Brat plugin has not updated your theme yet.

**Pull request merged**
