### PR TITLE
Border workspace layout partial overhaul, new features and formatting

### PR DESCRIPTION
**Pull request by notnotnescap**
First of all, sorry for mixing multiple unrelated changes in a single pull request, here is a detailed explanation for all the changes :
1. Border workspace layout overhaul : I improved the css rules to apply border radius correctly in almost every possible tab layout when the sidebars are closed.

before vs now
Screenshot 2024-10-28 at 13 37 17Screenshot 2024-10-28 at 13 37 38
before vs now
Screenshot 2024-10-28 at 13 38 14Screenshot 2024-10-28 at 13 38 37

2. I changed all indentation in scss files to 4 spaces to keep syntax consistent across files (was not sure if it should be 2 spaces or 4 spaces, please let me know if it needs to be changed to 2 spaces)
3. I added some features :
- Corner radius setting for embeds (File Editor & Markdown Elements>Embeds>anp-embed-corner-radius)
- Math block (LaTeX) font size setting (File Editor & Markdown Elements>LaTeX>anp-latex-block-font-size)
- A setting to hide the comments completely when not editing them (already a feature of reading mode, but now it works also in live preview)
- A setting to only hide the '%%' comment indicators when not editing them (Typography>Comments)
Screenshot 2024-10-28 at 14 13 07

### CODE REVIEW

**Comment by iwa** [comment]
your changes are reverting the changes made in #311 

see changes:
https://github.com/AnubisNekhet/AnuPpuccin/pull/319/files#diff-abc2eafd0ec30d77b03b4b6de9b4b86bc4988fdbe3e9e07a274e2a21762e6f90L162
https://github.com/AnubisNekhet/AnuPpuccin/pull/319/files#diff-083d22989d8db9699aaa45f98ed4004e40003be01cdf718026708e86002d31caL162

and for some reasons, the max embed height setting disappeared (is it intended?)
> current main
> image

> your fork
> image

**Comment by notnotnescap** [comment]
yep, seems like I overlooked those changes when merging. @iwa please double check that everything is there. I removed max-embed-height because it wasn't implemented from what I could tell.

**Comment by notnotnescap** [comment]
I think this is ready to be merged, @AnubisNekhet please review the changes when you have some time.

**Comment by AnubisNekhet** [comment]
I'm a bit preoccupied with work right now, I'll review the PR in a few days.

**Comment by AnubisNekhet** [comment]
LGTM

**Pull request merged**
